### ISSUE TITLE
点发布按钮就显示错误，帖子发不出去

### ISSUE THREAD

**Issue by xubocai** [nodeloc/lottery#1]
![image](https://github.com/user-attachments/assets/47970ccc-66c4-4069-bb2c-e4c774c2131c)
![image](https://github.com/user-attachments/assets/6db61131-1eed-4f35-b2b9-26cbf52c9cda)

**Comment by nodeloc** [comment]
卸载旧版本，特别是数据库表，重装新版本。

**Comment by xubocai** [comment]
新的也是用这个命令去下载是吧“composer require nodeloc/lottery:"*"”
